import streamlit as st
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import numpy as np
import joblib
def generate_pdf_report(probability, risk_level):

    pdf_file = "fraud_report.pdf"

    c = canvas.Canvas(pdf_file, pagesize=letter)

    c.setFont("Helvetica-Bold", 20)
    c.drawString(180, 750, "Income Tax Fraud Report")

    c.setFont("Helvetica", 14)
    c.drawString(100, 680, f"Fraud Probability: {probability:.2%}")

    c.drawString(100, 640, f"Risk Level: {risk_level}")

    if probability >= 0.5:
        result = "FRAUD DETECTED"
    else:
        result = "NOT FRAUD"

    c.drawString(100, 600, f"Prediction Result: {result}")

    c.drawString(100, 540, "Generated by AI-Based Fraud Detection System")

    c.save()

    return pdf_file
# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------

st.set_page_config(
    page_title="Income Tax Fraud Detection",
    layout="wide"
)

# ---------------------------------------------------
# LOGIN SYSTEM
# ---------------------------------------------------

USERNAME = "admin"
PASSWORD = "1234"

st.sidebar.title("🔐 Login")

username = st.sidebar.text_input("Username")
password = st.sidebar.text_input(
    "Password",
    type="password"
)

if username != USERNAME or password != PASSWORD:
    st.warning("Please login to continue")
    st.stop()

# ---------------------------------------------------
# LOAD MODELS
# ---------------------------------------------------

rf_model = joblib.load(
    "model_artifacts/random_forest.pkl"
)

xgb_model = joblib.load(
    "model_artifacts/xgboost.pkl"
)

lr_model = joblib.load(
    "model_artifacts/logistic_regression.pkl"
)

scaler = joblib.load(
    "model_artifacts/scaler.pkl"
)

# ---------------------------------------------------
# TITLE
# ---------------------------------------------------

st.title("💳 Income Tax Fraud Detection System")

st.markdown("---")

tab1, tab2, tab3 = st.tabs([

    "🔍 Single Prediction",

    "📂 Batch Detection",

    "📊 Analytics Dashboard"

])
# ---------------------------------------------------
# INPUTS
# ---------------------------------------------------
with tab1:
    st.sidebar.header("🧾 Taxpayer Details")

    Annual_Income = st.sidebar.number_input(
    "Annual Income",
    min_value=200000,
    value=1000000
)

    Declared_Tax = st.sidebar.number_input(
    "Declared Tax",
    min_value=5000,
    value=200000
)

    Deduction_Risk = st.sidebar.slider(
        "Deduction Risk",
        0,
        100,
        50
    )

    Expense_Anomaly = st.sidebar.slider(
        "Expense Anomaly",
        0,
        100,
        50
    )

    Investment_Mismatch = st.sidebar.slider(
        "Investment Mismatch",
        0,
        100,
        50
    )

    Cash_Transaction_Risk = st.sidebar.slider(
        "Cash Transaction Risk",
        0,
        100,
        50
    )

    Business_Loss_Risk = st.sidebar.slider(
        "Business Loss Risk",
        0,
        100,
        50
    )

    Asset_Underreporting = st.sidebar.slider(
        "Asset Underreporting",
        0,
        100,
        50
    )

    Refund_Claim_Risk = st.sidebar.slider(
        "Refund Claim Risk",
        0,
        100,
        50
    )

    Compliance_Risk = st.sidebar.slider(
        "Compliance Risk",
        0,
        100,
        50
    )

    Income_Variation = st.sidebar.slider(
        "Income Variation",
        0,
        100,
        50
    )

    Previous_Audit_Flag = st.sidebar.radio(
        "Previous Audit Flag",
        [0, 1]
    )

    Penalty_History = st.sidebar.radio(
        "Penalty History",
        [0, 1]
    )

    High_Value_Transactions = st.sidebar.slider(
        "High Value Transactions",
        0,
        100,
        50
    )

    Foreign_Asset_Score = st.sidebar.slider(
        "Foreign Asset Score",
        0,
        100,
        50
    )

    GST_Mismatch = st.sidebar.radio(
        "GST Mismatch",
        [0, 1]
    )

    Suspicious_Deduction = st.sidebar.radio(
        "Suspicious Deduction",
        [0, 1]
    )

    Shell_Company_Link = st.sidebar.radio(
        "Shell Company Link",
        [0, 1]
    )

    Frequent_ITR_Revisions = st.sidebar.radio(
        "Frequent ITR Revisions",
        [0, 1]
    )

    Cash_Deposit_Spike = st.sidebar.radio(
        "Cash Deposit Spike",
        [0, 1]
    )

    High_Risk_Industry = st.sidebar.radio(
        "High Risk Industry",
        [0, 1]
    )

    # ---------------------------------------------------
    # CREATE DATAFRAME
    # ---------------------------------------------------

    input_data = pd.DataFrame([[
        Annual_Income,
        Declared_Tax,
        Deduction_Risk,
        Expense_Anomaly,
        Investment_Mismatch,
        Cash_Transaction_Risk,
        Business_Loss_Risk,
        Asset_Underreporting,
        Refund_Claim_Risk,
        Compliance_Risk,
        Income_Variation,
        Previous_Audit_Flag,
        Penalty_History,
        High_Value_Transactions,
        Foreign_Asset_Score,
        GST_Mismatch,
        Suspicious_Deduction,
        Shell_Company_Link,
        Frequent_ITR_Revisions,
        Cash_Deposit_Spike,
        High_Risk_Industry
    ]], columns=[

        "Annual_Income",
        "Declared_Tax",
        "Deduction_Risk",
        "Expense_Anomaly",
        "Investment_Mismatch",
        "Cash_Transaction_Risk",
        "Business_Loss_Risk",
        "Asset_Underreporting",
        "Refund_Claim_Risk",
        "Compliance_Risk",
        "Income_Variation",
        "Previous_Audit_Flag",
        "Penalty_History",
        "High_Value_Transactions",
        "Foreign_Asset_Score",
        "GST_Mismatch",
        "Suspicious_Deduction",
        "Shell_Company_Link",
        "Frequent_ITR_Revisions",
        "Cash_Deposit_Spike",
        "High_Risk_Industry"

    ])

    # ---------------------------------------------------
    # SCALE INPUT
    # ---------------------------------------------------

    scaled_input = scaler.transform(input_data)

    # ---------------------------------------------------
    # PREDICTION
    # ---------------------------------------------------

    if st.button("🚨 Predict Fraud"):

        rf_prob = rf_model.predict_proba(
            scaled_input
        )[0][1]

        xgb_prob = xgb_model.predict_proba(
            scaled_input
        )[0][1]

        lr_prob = lr_model.predict_proba(
            scaled_input
        )[0][1]

        final_probability = rf_prob

        # ---------------------------------------------------
        # RESULT
        # ---------------------------------------------------

        st.subheader("📊 Prediction Result")

        if final_probability >= 0.5:
            st.error("🚨 FRAUD DETECTED")
        else:
            st.success("✅ NOT FRAUD")

        st.metric(
            "Fraud Probability",
            f"{final_probability:.2%}"
        )
        st.progress(float(final_probability))
        # ---------------------------------------------------
        # RISK LEVEL
        # ---------------------------------------------------

        if final_probability < 0.30:
            risk = "🟢 LOW RISK"

        elif final_probability < 0.60:
            risk = "🟡 MEDIUM RISK"

        elif final_probability < 0.80:
            risk = "🟠 HIGH RISK"

        else:
            risk = "🔴 CRITICAL RISK"

        st.subheader(f"Risk Level: {risk}")
        pdf_path = generate_pdf_report(final_probability, risk)

if 'pdf_path' in locals():
    with open(pdf_path, "rb") as pdf_file:
        st.download_button(
        label="📥 Download Fraud Report",
        data=pdf_file,
        file_name="fraud_report.pdf",
        mime="application/pdf"
    )

        # ---------------------------------------------------
        # MODEL COMPARISON
        # ---------------------------------------------------
if 'rf_prob' in locals():
    st.subheader("📈 Model Comparison")

    comparison_df = pd.DataFrame({

            "Model": [
                "Random Forest",
                "XGBoost",
                "Logistic Regression"
            ],

            "Fraud Probability": [
                rf_prob,
                xgb_prob,
                lr_prob
            ]

        })

    st.dataframe(comparison_df)

        # ---------------------------------------------------
        # FRAUD REASONS
        # ---------------------------------------------------

# ---------------------------------------------------
# FRAUD REASONS
# ---------------------------------------------------

reasons = []

if GST_Mismatch == 1:
    reasons.append("GST mismatch detected")

if Suspicious_Deduction == 1:
    reasons.append("Suspicious deductions found")

if Shell_Company_Link == 1:
    reasons.append("Possible shell company linkage")

if Cash_Deposit_Spike == 1:
    reasons.append("Abnormal cash deposit spike")

if Asset_Underreporting >= 50:
    reasons.append("Possible asset underreporting")

if High_Value_Transactions >= 50:
    reasons.append("Large number of high-value transactions")

st.subheader("🧠 Fraud Explanation")

if len(reasons) > 0:

        for r in reasons:
            st.warning(r)

else:
        st.success(
            "No major fraud indicators found"
        )
        # ---------------------------------------------------
# BATCH CSV PREDICTION
# ---------------------------------------------------
with tab2:
    st.markdown("---")
    st.header("📂 Batch Fraud Detection")

    uploaded_file = st.file_uploader(
        "Upload CSV File",
        type=["csv"]
    )

    if uploaded_file is not None:

        batch_data = pd.read_csv(uploaded_file)

        st.subheader("Uploaded Dataset")

        st.dataframe(batch_data.head())

        try:

            scaled_batch = scaler.transform(batch_data)

            rf_probs = rf_model.predict_proba(
                scaled_batch
            )[:,1]

            xgb_probs = xgb_model.predict_proba(
                scaled_batch
            )[:,1]

            lr_probs = lr_model.predict_proba(
                scaled_batch
            )[:,1]

            final_probs = (
                rf_probs +
                xgb_probs +
                lr_probs
            ) / 3

            batch_data["Fraud Probability"] = final_probs

            batch_data["Prediction"] = np.where(
                final_probs >= 0.5,
                "Fraud",
                "Not Fraud"
            )

            st.subheader("Prediction Results")

            st.dataframe(batch_data)

            csv = batch_data.to_csv(index=False)

            st.download_button(
                "⬇ Download Results",
                csv,
                "fraud_results.csv",
                "text/csv"
            )

        except Exception as e:
            st.error(f"Error: {e}") 
with tab3:

    st.header("📊 Fraud Analytics Dashboard")

    chart_data = pd.DataFrame({

        "Model": [
            "Logistic Regression",
            "Random Forest",
            "XGBoost"
        ],

        "Accuracy": [
            0.995,
            0.906,
            0.949
        ]
    })

    st.subheader("📈 Model Accuracy Comparison")

    st.bar_chart(
        chart_data.set_index("Model")
    )

    risk_data = pd.DataFrame({

        "Risk Type": [
            "Deduction Risk",
            "Expense Anomaly",
            "Investment Mismatch",
            "Cash Transaction"
        ],

        "Score": [
            Deduction_Risk,
            Expense_Anomaly,
            Investment_Mismatch,
            Cash_Transaction_Risk
        ]
    })

    st.subheader("⚠️ Risk Score Analysis")

    st.line_chart(
        risk_data.set_index("Risk Type")
    )
 

st.subheader("📋 System Insights")

st.info(
    "The system uses ensemble machine learning "
    "models to detect suspicious tax filing patterns."
)